name: uddipan
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  audioplayers: ^5.2.0
  flutter_spinkit: ^5.2.0
  carousel_slider:
  smooth_page_indicator:
  http: ^1.1.2
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  dotted_border: ^2.1.0
  flutter_rating_bar: ^4.0.1
  animated_splash_screen: ^1.3.0
  photo_view: ^0.14.0
  flutter:
    sdk: flutter
  get_storage: ^2.1.1
  flutter_screenutil: ^5.9.0
  dio: ^5.4.0
  intl: ^0.18.1
  restart_app: ^1.2.1
  zego_uikit_prebuilt_call: ^3.17.9
  font_awesome_flutter: ^10.6.0
  awesome_bottom_bar: ^1.2.4
  badges: ^3.1.2
  intl_phone_field: ^3.2.0
  shared_preferences: ^2.2.1
  dots_indicator: ^3.0.0
  fast_cached_network_image: ^1.2.0
  shimmer: ^3.0.0
  image_picker: ^1.0.7
  flutter_sslcommerz: ^2.2.2-nullsafety.0
  fluttertoast: ^8.2.4
  animated_custom_dropdown: ^1.5.0
  firebase_core: ^2.25.0
  firebase_messaging: ^14.7.11
  flutter_local_notifications: ^16.3.2
  file_picker: ^6.1.1
  url_launcher: ^6.3.0
  date_picker_timeline: ^1.2.5
  flutter_cached_pdfview: ^0.4.2
  uri: ^1.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/sounds/
    - assets/svg/
    - assets/fonts/
  fonts:
    - family: monstserrat
      fonts:
        - asset: assets/fonts/montserrat_regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat_medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat_bold.ttf
          weight: 700
